const path              = require('path'),
      SRC               = path.join(__dirname, 'src/'),
      NODE_MODULES      = path.join(__dirname, 'node_modules/'),
      webpack           = require('webpack'),
      ExtractTextPlugin = require('extract-text-webpack-plugin'),
      StyleLintPlugin   = require('stylelint-webpack-plugin');

const config = {
  entry: './src/app.js',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  resolve: {
    modules: [
      SRC,
      NODE_MODULES,
      path.join(SRC, 'assets/scripts'),
      path.join(SRC, 'assets/sass'),
      path.join(SRC, 'assets/images'),
      path.join(SRC, 'assets/icons')
    ]
  },
  devtool: 'cheap-eval-source-map',
  module: {
    rules: [
      {
        test: /\.s?css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
            },
            {
              loader: 'postcss-loader',
              options: {
                ident: 'postcss',
                plugins: [
                  require('autoprefixer')({ browsers: 'last 2 versions' }),
                  require('css-mqpacker')({ sort: true }),
                ],
              }
            },
            {
              loader: 'sass-loader',
              options: {
                includePaths: [
                  'node_modules/sanitize.scss'
                ],
              }
            }
          ]
        })
      },
      {
        test: /\.svg$/,
        use: [
          'svg-sprite-loader',
          'svgo-loader'
        ]
      },
      {
        test: /\.(jpe?g|png|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              outputPath: 'images/',
              name: '[name].[ext]'
            }
          },
          'img-loader'
        ]
      },
      {
        enforce: 'pre',
        test: /\.js$/,
        exclude: [
          /node_modules/
        ],
        loader: 'eslint-loader'
      },
      {
        test: /\.js$/,
        exclude: [
          /node_modules/
        ],
        loader: 'babel-loader'
      }
    ]
  },
  plugins: [
    new webpack.BannerPlugin('This file is autogenerated with Webpack. DO NOT EDIT DIRECTLY.'),
    new StyleLintPlugin(),
    new ExtractTextPlugin('app.css')
  ]
};

module.exports = config;
