// flow-typed signature: 6af8affb5d8a43b2fdfbe1b0b095af6c
// flow-typed version: <<STUB>>/browser-sync-webpack-plugin_v^2.2.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-sync-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-sync-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-sync-webpack-plugin/lib/BrowserSyncPlugin' {
  declare module.exports: any;
}

declare module 'browser-sync-webpack-plugin/lib/getCssOnlyEmittedAssetsNames' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-sync-webpack-plugin/index' {
  declare module.exports: $Exports<'browser-sync-webpack-plugin'>;
}
declare module 'browser-sync-webpack-plugin/index.js' {
  declare module.exports: $Exports<'browser-sync-webpack-plugin'>;
}
declare module 'browser-sync-webpack-plugin/lib/BrowserSyncPlugin.js' {
  declare module.exports: $Exports<'browser-sync-webpack-plugin/lib/BrowserSyncPlugin'>;
}
declare module 'browser-sync-webpack-plugin/lib/getCssOnlyEmittedAssetsNames.js' {
  declare module.exports: $Exports<'browser-sync-webpack-plugin/lib/getCssOnlyEmittedAssetsNames'>;
}
