// flow-typed signature: fa0e9720333e801bde860013ef22a053
// flow-typed version: <<STUB>>/kss_v^3.0.0-beta.19/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kss/builder/base/example/index' {
  declare module.exports: any;
}

declare module 'kss/builder/base/example/kss_builder_base_example' {
  declare module.exports: any;
}

declare module 'kss/builder/base/handlebars/index' {
  declare module.exports: any;
}

declare module 'kss/builder/base/handlebars/kss_builder_base_handlebars' {
  declare module.exports: any;
}

declare module 'kss/builder/base/index' {
  declare module.exports: any;
}

declare module 'kss/builder/base/kss_builder_base' {
  declare module.exports: any;
}

declare module 'kss/builder/base/nunjucks/index' {
  declare module.exports: any;
}

declare module 'kss/builder/base/nunjucks/kss_builder_base_nunjucks' {
  declare module.exports: any;
}

declare module 'kss/builder/base/twig/extend-drupal8/drupal8-extensions' {
  declare module.exports: any;
}

declare module 'kss/builder/base/twig/index' {
  declare module.exports: any;
}

declare module 'kss/builder/base/twig/kss_builder_base_twig' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/builder' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/kss-assets/kss-fullscreen' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/kss-assets/kss-guides' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/kss-assets/kss-markup' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/kss-assets/kss' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/kss-assets/prettify' {
  declare module.exports: any;
}

declare module 'kss/builder/handlebars/kss-assets/scrollspy' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/builder' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/kss-assets/kss-fullscreen' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/kss-assets/kss-guides' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/kss-assets/kss-markup' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/kss-assets/kss' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/kss-assets/prettify' {
  declare module.exports: any;
}

declare module 'kss/builder/nunjucks/kss-assets/scrollspy' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/builder' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/kss-assets/kss-fullscreen' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/kss-assets/kss-guides' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/kss-assets/kss-markup' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/kss-assets/kss' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/kss-assets/prettify' {
  declare module.exports: any;
}

declare module 'kss/builder/twig/kss-assets/scrollspy' {
  declare module.exports: any;
}

declare module 'kss/lib/cli' {
  declare module.exports: any;
}

declare module 'kss/lib/kss_modifier' {
  declare module.exports: any;
}

declare module 'kss/lib/kss_parameter' {
  declare module.exports: any;
}

declare module 'kss/lib/kss_section' {
  declare module.exports: any;
}

declare module 'kss/lib/kss_style_guide' {
  declare module.exports: any;
}

declare module 'kss/lib/kss' {
  declare module.exports: any;
}

declare module 'kss/lib/parse' {
  declare module.exports: any;
}

declare module 'kss/lib/traverse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kss/builder/base/example/index.js' {
  declare module.exports: $Exports<'kss/builder/base/example/index'>;
}
declare module 'kss/builder/base/example/kss_builder_base_example.js' {
  declare module.exports: $Exports<'kss/builder/base/example/kss_builder_base_example'>;
}
declare module 'kss/builder/base/handlebars/index.js' {
  declare module.exports: $Exports<'kss/builder/base/handlebars/index'>;
}
declare module 'kss/builder/base/handlebars/kss_builder_base_handlebars.js' {
  declare module.exports: $Exports<'kss/builder/base/handlebars/kss_builder_base_handlebars'>;
}
declare module 'kss/builder/base/index.js' {
  declare module.exports: $Exports<'kss/builder/base/index'>;
}
declare module 'kss/builder/base/kss_builder_base.js' {
  declare module.exports: $Exports<'kss/builder/base/kss_builder_base'>;
}
declare module 'kss/builder/base/nunjucks/index.js' {
  declare module.exports: $Exports<'kss/builder/base/nunjucks/index'>;
}
declare module 'kss/builder/base/nunjucks/kss_builder_base_nunjucks.js' {
  declare module.exports: $Exports<'kss/builder/base/nunjucks/kss_builder_base_nunjucks'>;
}
declare module 'kss/builder/base/twig/extend-drupal8/drupal8-extensions.js' {
  declare module.exports: $Exports<'kss/builder/base/twig/extend-drupal8/drupal8-extensions'>;
}
declare module 'kss/builder/base/twig/index.js' {
  declare module.exports: $Exports<'kss/builder/base/twig/index'>;
}
declare module 'kss/builder/base/twig/kss_builder_base_twig.js' {
  declare module.exports: $Exports<'kss/builder/base/twig/kss_builder_base_twig'>;
}
declare module 'kss/builder/handlebars/builder.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/builder'>;
}
declare module 'kss/builder/handlebars/kss-assets/kss-fullscreen.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/kss-assets/kss-fullscreen'>;
}
declare module 'kss/builder/handlebars/kss-assets/kss-guides.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/kss-assets/kss-guides'>;
}
declare module 'kss/builder/handlebars/kss-assets/kss-markup.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/kss-assets/kss-markup'>;
}
declare module 'kss/builder/handlebars/kss-assets/kss.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/kss-assets/kss'>;
}
declare module 'kss/builder/handlebars/kss-assets/prettify.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/kss-assets/prettify'>;
}
declare module 'kss/builder/handlebars/kss-assets/scrollspy.js' {
  declare module.exports: $Exports<'kss/builder/handlebars/kss-assets/scrollspy'>;
}
declare module 'kss/builder/nunjucks/builder.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/builder'>;
}
declare module 'kss/builder/nunjucks/kss-assets/kss-fullscreen.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/kss-assets/kss-fullscreen'>;
}
declare module 'kss/builder/nunjucks/kss-assets/kss-guides.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/kss-assets/kss-guides'>;
}
declare module 'kss/builder/nunjucks/kss-assets/kss-markup.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/kss-assets/kss-markup'>;
}
declare module 'kss/builder/nunjucks/kss-assets/kss.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/kss-assets/kss'>;
}
declare module 'kss/builder/nunjucks/kss-assets/prettify.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/kss-assets/prettify'>;
}
declare module 'kss/builder/nunjucks/kss-assets/scrollspy.js' {
  declare module.exports: $Exports<'kss/builder/nunjucks/kss-assets/scrollspy'>;
}
declare module 'kss/builder/twig/builder.js' {
  declare module.exports: $Exports<'kss/builder/twig/builder'>;
}
declare module 'kss/builder/twig/kss-assets/kss-fullscreen.js' {
  declare module.exports: $Exports<'kss/builder/twig/kss-assets/kss-fullscreen'>;
}
declare module 'kss/builder/twig/kss-assets/kss-guides.js' {
  declare module.exports: $Exports<'kss/builder/twig/kss-assets/kss-guides'>;
}
declare module 'kss/builder/twig/kss-assets/kss-markup.js' {
  declare module.exports: $Exports<'kss/builder/twig/kss-assets/kss-markup'>;
}
declare module 'kss/builder/twig/kss-assets/kss.js' {
  declare module.exports: $Exports<'kss/builder/twig/kss-assets/kss'>;
}
declare module 'kss/builder/twig/kss-assets/prettify.js' {
  declare module.exports: $Exports<'kss/builder/twig/kss-assets/prettify'>;
}
declare module 'kss/builder/twig/kss-assets/scrollspy.js' {
  declare module.exports: $Exports<'kss/builder/twig/kss-assets/scrollspy'>;
}
declare module 'kss/index' {
  declare module.exports: $Exports<'kss'>;
}
declare module 'kss/index.js' {
  declare module.exports: $Exports<'kss'>;
}
declare module 'kss/lib/cli.js' {
  declare module.exports: $Exports<'kss/lib/cli'>;
}
declare module 'kss/lib/kss_modifier.js' {
  declare module.exports: $Exports<'kss/lib/kss_modifier'>;
}
declare module 'kss/lib/kss_parameter.js' {
  declare module.exports: $Exports<'kss/lib/kss_parameter'>;
}
declare module 'kss/lib/kss_section.js' {
  declare module.exports: $Exports<'kss/lib/kss_section'>;
}
declare module 'kss/lib/kss_style_guide.js' {
  declare module.exports: $Exports<'kss/lib/kss_style_guide'>;
}
declare module 'kss/lib/kss.js' {
  declare module.exports: $Exports<'kss/lib/kss'>;
}
declare module 'kss/lib/parse.js' {
  declare module.exports: $Exports<'kss/lib/parse'>;
}
declare module 'kss/lib/traverse.js' {
  declare module.exports: $Exports<'kss/lib/traverse'>;
}
