// flow-typed signature: 18f60eb241cc87120372fe0b765a20c6
// flow-typed version: <<STUB>>/sanitize.scss_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.scss' {
  declare module.exports: any;
}
