// flow-typed signature: ee6b68aa0b42706438d0bb2b22f84cc7
// flow-typed version: <<STUB>>/stylelint-config-wordpress_v^12.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-wordpress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-wordpress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-wordpress/scss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-wordpress/index' {
  declare module.exports: $Exports<'stylelint-config-wordpress'>;
}
declare module 'stylelint-config-wordpress/index.js' {
  declare module.exports: $Exports<'stylelint-config-wordpress'>;
}
declare module 'stylelint-config-wordpress/scss.js' {
  declare module.exports: $Exports<'stylelint-config-wordpress/scss'>;
}
